# Generated by Django 3.2 on 2021-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerqueue_queuetimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerqueue',
            name='shop_name',
            field=models.CharField(default='Default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerqueue',
            name='shopkeeper_phone',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
