# Generated by Django 3.2.2 on 2021-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_covidalert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerEmail', models.EmailField(max_length=254)),
                ('delivery_address', models.TextField()),
                ('delivery_pin', models.IntegerField()),
                ('delivery_district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerFirstName', models.CharField(max_length=30)),
                ('customerLastName', models.CharField(max_length=30)),
                ('shopkeeper_email', models.EmailField(max_length=254)),
                ('shop_name', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=120)),
                ('item_price', models.FloatField()),
                ('currentdate', models.DateTimeField()),
            ],
        ),
    ]
