# Generated by Django 3.2 on 2021-05-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_rename_q_solt_capacity_shops_q_slot_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='owner_email',
            new_name='shopkeeper',
        ),
    ]
