# Generated by Django 3.2 on 2021-05-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_rename_owner_email_shops_shopkeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='shopkeeper',
            new_name='shopkeeper_email',
        ),
    ]
