# Generated by Django 3.2 on 2021-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_rename_shopkeeper_shops_shopkeeper_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='id',
        ),
        migrations.AlterField(
            model_name='shops',
            name='shopkeeper_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
