# Generated by Django 3.2 on 2021-06-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_shopregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainmentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
                ('localbody', models.CharField(max_length=30)),
                ('wardnum', models.IntegerField()),
                ('announced_date', models.DateTimeField()),
            ],
        ),
    ]
