# Generated by Django 3.2 on 2021-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_remove_containmentzone_announced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopregistry',
            name='dateEntry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
