# Generated by Django 3.2 on 2021-06-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_shopregistry_dateentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistry',
            name='dateEntry',
            field=models.DateTimeField(),
        ),
    ]
