# Generated by Django 3.2.2 on 2021-07-11 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_alter_shopregistry_dateentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper_email', models.EmailField(max_length=254)),
                ('item_name', models.CharField(max_length=120)),
                ('item_price', models.FloatField()),
                ('item_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('item_description', models.TextField(blank=True)),
            ],
        ),
    ]
